# Use a lightweight Nginx image
FROM nginx:alpine

# Copy the frontend files to the Nginx html directory
COPY ./frontend /usr/share/nginx/html

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80
